### ISSUE TITLE
The name "upstart" collides with an ubuntu package

### ISSUE THREAD

**Issue by tfoote** [clearpathrobotics/robot_upstart#1]
It should be renamed.

**Comment by mikepurvis** [comment]
Happy to change it—would robot_upstart be acceptable?

For my understanding, though, what are the contexts in which the conflict is an issue? From the end-user's perspective, "upstart" and "ros-hydro-upstart" are different packages.

**Comment by tfoote** [comment]
There will be issues when you start trying to install things that depend on
"upstart" as it won't know if you're looking for the rosdep or the
package.  And we often refer to packages w/o the full name which makes "did
you install the upstart package?" ambiguious.

**Comment by tfoote** [comment]
robot_upstart is much better.

**Comment by mikepurvis** [comment]
Changed to robot_upstart.
