### ISSUE TITLE
templates/job-start.em has bad {user} tokens

### ISSUE THREAD

**Issue by tappan-at-git** [clearpathrobotics/robot_upstart#26]
templates/job-start.em has at least one instance of `{user}` being used where you really want `@(user)`. When creating the ROS log directory if it doesn't exist ([here](https://github.com/clearpathrobotics/robot_upstart/blob/jade-devel/templates/job-start.em#L40)):

```
if [[ ! -d $log_path ]]; then
  CREATED_LOGDIR=true
  trap 'CREATED_LOGDIR=false' ERR
    log warn "@(name): The log directory you specified \"$log_path\" does not exist. Attempting to create."
    mkdir -p $log_path 2>/dev/null
    chown {user}:{user} $log_path 2>/dev/null
    chmod ug+wr $log_path 2>/dev/null
  trap - ERR
  # if log_path could not be created, default to tmp
  if [[ $CREATED_LOGDIR == false ]]; then
    log warn "@(name): The log directory you specified \"$log_path\" cannot be created. Defaulting to \"/tmp\"!"
    log_path="/tmp"
  fi
fi
```

I only discovered this when trying to make a job with ROS_LOG_DIR set to `/dev/shm/rosLogs`.

**Comment by mikepurvis** [comment]
Jade: e5917621ca8ecfecf8281f2f679f7620a287c213

Indigo: ebc39bee1ca743d12d405fba1b21c509728a90ad
