### ISSUE TITLE
Issue setting a launch file to run on upstart (need more than 1 value to unpack)

### ISSUE THREAD

**Issue by gabrielarpino** [clearpathrobotics/robot_upstart#38]
OLD ISSUE:

> Hi,
> 
> I am trying to run my launch file on startup and have tried to follow the commands on this page : http://docs.ros.org/jade/api/robot_upstart/html/# , but when I run `rosrun robot_upstart install r200_nodelet_rgbd_startup.launch` (with the launch file placed in the /opt/ros/indigo/share/robot_upstart folder), I get the following error:
> 
> ```
> 
> administrator@CPR-J100-0019:/opt/ros/indigo/share/robot_upstart$ rosrun robot_upstart install r200_nodelet_rgbd_startup.launch 
> Traceback (most recent call last):
>   File "/opt/ros/indigo/lib/robot_upstart/install", line 32, in <module>
>     exit(main())
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/robot_upstart/install_script.py", line 66, in main
>     pkg, pkgpath = args.pkgpath[0].split('/', 1)
> ValueError: need more than 1 value to unpack
> ```
> 
> Please let me know if there is any solution to this issue, thank you very much for the help. 
> 
> Best,
> 
> Gabriel

NEW ISSUE: Figured it out. The naming convention for the launch file path is package_name/path_to_file. 

The issue I am having now is that, after having installed a .launch file for Jackal to launch when booting up, the jackal is very slow and it's command line through ssh is very slow. I am also not able to echo any of my desired topics, as they simply hang after I type "rostopic echo /my_topic". Let me know if there could be any solution to this, Thanks.

**Comment by mikepurvis** [comment]
The perf issue looks unrelated to robot_upstart, so I'm to close this. Please contact Clearpath Support for help on that if it's still a problem.
