### ISSUE TITLE
Adding a --wait flag to launch file to the install script

### ISSUE THREAD

**Issue by msadowski** [clearpathrobotics/robot_upstart#72]
Hi!

This might be slightly tangential to #16. I noticed that the only clean way to add a --wait flag to the launch file is through the python API?

In a system with multiple machines and a single master it might be desired to wait for the master to start launchfiles (otherwise a launch will not be successful if it's execute before master comes up).

I'm more than happy to try to add this feature and make a PR if you think it's desired.

**Comment by 130s** [comment]
I think this is addressed already by https://github.com/clearpathrobotics/robot_upstart/pull/73

**Comment by msadowski** [comment]
Yes it is, closing it!
